### ISSUE TITLE
Adding this mod to existing world (or removing it) alters worldgen.

### ISSUE THREAD

**Issue by Lgmrszd** [Wouink/furnish#2]
After playing Create: Above and Beyond pack for a while, I decided to add this mod to existing world. After exploring new chunks, me and my friend noticed some anomalies at the chunk borders:

![изображение](https://user-images.githubusercontent.com/16291541/144722340-111cf88d-7812-4ce8-a719-f980e245e701.png)
![изображение](https://user-images.githubusercontent.com/16291541/144722346-d9c20daa-9846-49f3-811e-40addace14a8.png)

### One thing I noticed, when I tried same seed with and without this mod, this area was the same:
With Furnish:
![изображение](https://user-images.githubusercontent.com/16291541/144722406-09616a27-94e3-440f-836b-681d207a705d.png)
Without Furnish:
![изображение](https://user-images.githubusercontent.com/16291541/144722440-6da676e0-98c3-46ba-a346-2a84ba74f39f.png)
With Furnish at the start, and then removing it:
![изображение](https://user-images.githubusercontent.com/16291541/144722456-71f5c8f3-effd-41ef-a587-5a3d98e53bd5.png)

### Important info:

Versions:
Create: Above and Beyond (pack): 1.2
Furnish: 0.3-fix1

**Comment by Wouink** [comment]
Hi, first, sorry for your world.

This is not related to Furnish which has litteraly no code changing world generation. I do have two possibilities regarding the source of this issue:
* You may have installed other mods at the same time you installed Furnish, those mods might change world generation.
* It can happen when registries change in Forge (adding new blocks). In this case, it's not directly related to Furnish but rather to how Forge handles this.

Anyway, I'm sorry to say I can do nothing for that kind of issue, this kind of thing just happens when modding your game.
Therefore, I'm closing the issue, but thanks for reporting.

Have a great day.
