### ISSUE TITLE
weird block breaking behavior after update to furnish-18-1.19

### ISSUE THREAD

**Issue by JasonKillsUs** [Wouink/furnish#21]
MC 1.19.2 Forge 43.2.3 ...
i updated Furnish from furnish-1.19-0.6.2 to furnish-18-1.19, now i can´t break any kind of stone Block anymore. I can break Sand and Dirt, Gravel but no stone of any sort. Reverting to 1.19-0.6.2 solves the problem.
Thanks for looking into it.

**Comment by Chokedamp** [comment]
I'm having the same issue. Exactly the same setup: Minecraft 1.19.2, Forge 43.2.3, furnish-18-1.19. latest.log doesn't seem to contain useful information.

This update has essentially removed the "Adequate Tool" property from stone blocks of all kinds. They take much longer to be mined and never drop anything. You can't even use a Stone Pickaxe from a Bonus Chest to mine your way past Stone and into Iron, because ores don't drop anything either.

**Comment by solohunt83** [comment]
I've had this issue as well. though i am using Forge 44.1.16 with minecraft ver. 1.19.3

**Comment by Wouink** [comment]
Hi,
Thanks for reporting.
This was fixed in Furnish v20+. Please download Furnish v21 which also fixes a rendering bug.
Sorry for the inconvenience!
